# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- release/*

pool:
  vmImage: 'ubuntu-latest'
steps:
- bash : | 
    echo "##vso[task.setvariable variable=mod_version]$(grep 'mod_version' ./gradle.properties | grep -P -o '(\d+.\d+.\d+)')"
- bash: |
    echo "##vso[task.setvariable variable=archives_basename]$(grep 'archives_base_name' ./gradle.properties | grep -P -o "(?<=\=).*" | sed -e 's/^[ \t]*//')"
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    tasks: 'build'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_Levoment'
    repositoryName: 'Levoment/SuperAxes'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'  
    title: '$(archives_basename) $(mod_version)'
    assets: '$(Pipeline.Workspace)/s/build/libs/*'
    addChangeLog: false